const Order = require('./models/Order');

const ordersSeed = [
  {
    streetAddress: '52732 Transport Place',
    city: 'Dearborn',
    state: 'MI',
    zipCode: 39990,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '25 Clove Junction',
    city: 'Tacoma',
    state: 'WA',
    zipCode: 32834,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '31781 Drewry Avenue',
    city: 'Corpus Christi',
    state: 'TX',
    zipCode: 81470,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '72655 Riverside Lane',
    city: 'Seattle',
    state: 'WA',
    zipCode: 67007,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '06 Northport Place',
    city: 'Oakland',
    state: 'CA',
    zipCode: 80806,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '94624 Park Meadow Point',
    city: 'Cincinnati',
    state: 'OH',
    zipCode: 79943,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '001 Lerdahl Place',
    city: 'Decatur',
    state: 'GA',
    zipCode: 77814,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '11 Bay Alley',
    city: 'Hartford',
    state: 'CT',
    zipCode: 40168,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '0 Namekagon Junction',
    city: 'San Angelo',
    state: 'TX',
    zipCode: 99505,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '8198 Luster Drive',
    city: 'Washington',
    state: 'DC',
    zipCode: 40229,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '6984 Sachtjen Drive',
    city: 'Sarasota',
    state: 'FL',
    zipCode: 71621,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '09 Brentwood Crossing',
    city: 'Washington',
    state: 'DC',
    zipCode: 98491,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '9275 Esker Parkway',
    city: 'Arlington',
    state: 'TX',
    zipCode: 78307,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '09 Pawling Place',
    city: 'Beaumont',
    state: 'TX',
    zipCode: 25259,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '0 Anzinger Center',
    city: 'San Francisco',
    state: 'CA',
    zipCode: 41226,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '4501 Springs Avenue',
    city: 'Portland',
    state: 'OR',
    zipCode: 27815,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '76 Wayridge Drive',
    city: 'Colorado Springs',
    state: 'CO',
    zipCode: 29485,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '284 Southridge Park',
    city: 'Little Rock',
    state: 'AR',
    zipCode: 67380,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '1397 Anhalt Center',
    city: 'Baltimore',
    state: 'MD',
    zipCode: 73742,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '3 Dottie Court',
    city: 'Peoria',
    state: 'IL',
    zipCode: 27151,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '18 Marquette Center',
    city: 'Tempe',
    state: 'AZ',
    zipCode: 55038,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '12 Lukken Avenue',
    city: 'Young America',
    state: 'MN',
    zipCode: 14286,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '142 Merrick Alley',
    city: 'Winston Salem',
    state: 'NC',
    zipCode: 48717,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '82344 Delladonna Point',
    city: 'Jefferson City',
    state: 'MO',
    zipCode: 73746,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '666 Londonderry Trail',
    city: 'New York City',
    state: 'NY',
    zipCode: 52722,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '7 Autumn Leaf Avenue',
    city: 'Baltimore',
    state: 'MD',
    zipCode: 49677,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '773 Sugar Pass',
    city: 'Amarillo',
    state: 'TX',
    zipCode: 37910,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '16 Loomis Park',
    city: 'Chicago',
    state: 'IL',
    zipCode: 39671,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '512 Oak Valley Pass',
    city: 'Hot Springs National Park',
    state: 'AR',
    zipCode: 12427,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '6456 Shasta Alley',
    city: 'Fresno',
    state: 'CA',
    zipCode: 98598,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '0894 Manitowish Junction',
    city: 'Atlanta',
    state: 'GA',
    zipCode: 40764,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '1444 Main Street',
    city: 'Brockton',
    state: 'MA',
    zipCode: 89610,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '3 Dexter Lane',
    city: 'Honolulu',
    state: 'HI',
    zipCode: 77386,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '3 Sauthoff Lane',
    city: 'South Lake Tahoe',
    state: 'CA',
    zipCode: 75947,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '0 Independence Place',
    city: 'Cleveland',
    state: 'OH',
    zipCode: 97954,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '6504 Hudson Alley',
    city: 'Atlanta',
    state: 'GA',
    zipCode: 38498,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '542 Sullivan Pass',
    city: 'Fort Worth',
    state: 'TX',
    zipCode: 81134,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '9 East Pass',
    city: 'Montpelier',
    state: 'VT',
    zipCode: 73534,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '7052 Miller Place',
    city: 'Spring',
    state: 'TX',
    zipCode: 60769,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '812 Lakewood Drive',
    city: 'El Paso',
    state: 'TX',
    zipCode: 21328,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '8 Morrow Court',
    city: 'Washington',
    state: 'DC',
    zipCode: 55250,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '5521 Golden Leaf Alley',
    city: 'Irvine',
    state: 'CA',
    zipCode: 26987,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '8 Jenifer Point',
    city: 'New York City',
    state: 'NY',
    zipCode: 27957,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '1 Bunker Hill Lane',
    city: 'Cincinnati',
    state: 'OH',
    zipCode: 47573,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '39092 Fallview Parkway',
    city: 'Houston',
    state: 'TX',
    zipCode: 69611,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '3490 Sloan Circle',
    city: 'Miami',
    state: 'FL',
    zipCode: 32157,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '353 Emmet Street',
    city: 'Lawrenceville',
    state: 'GA',
    zipCode: 96813,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '392 Mayer Lane',
    city: 'Lexington',
    state: 'KY',
    zipCode: 57923,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '38 Manitowish Lane',
    city: 'Richmond',
    state: 'VA',
    zipCode: 61689,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '5 Milwaukee Hill',
    city: 'Charlotte',
    state: 'NC',
    zipCode: 49818,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '55243 Kipling Way',
    city: 'Birmingham',
    state: 'AL',
    zipCode: 97063,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '2 Warbler Alley',
    city: 'Kansas City',
    state: 'MO',
    zipCode: 49897,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '69 Fuller Parkway',
    city: 'Mc Keesport',
    state: 'PA',
    zipCode: 70103,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '36911 Grayhawk Road',
    city: 'Jamaica',
    state: 'NY',
    zipCode: 64808,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '98 Scoville Pass',
    city: 'Cincinnati',
    state: 'OH',
    zipCode: 46420,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '542 Utah Drive',
    city: 'Chattanooga',
    state: 'TN',
    zipCode: 58401,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '317 Bluejay Circle',
    city: 'Spokane',
    state: 'WA',
    zipCode: 91158,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '943 1st Crossing',
    city: 'Atlanta',
    state: 'GA',
    zipCode: 86050,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '6 Coleman Plaza',
    city: 'Colorado Springs',
    state: 'CO',
    zipCode: 29478,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '93680 Amoth Hill',
    city: 'Las Vegas',
    state: 'NV',
    zipCode: 40817,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '838 Briar Crest Street',
    city: 'Cleveland',
    state: 'OH',
    zipCode: 94709,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '80 Anthes Avenue',
    city: 'Pittsburgh',
    state: 'PA',
    zipCode: 27835,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '99241 Ilene Lane',
    city: 'Cincinnati',
    state: 'OH',
    zipCode: 63004,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '59183 Sunbrook Street',
    city: 'El Paso',
    state: 'TX',
    zipCode: 27444,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '8 Kenwood Parkway',
    city: 'Troy',
    state: 'MI',
    zipCode: 49920,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '514 Rowland Junction',
    city: 'Spokane',
    state: 'WA',
    zipCode: 19313,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '4 Kedzie Street',
    city: 'Meridian',
    state: 'MS',
    zipCode: 22158,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '96 Moulton Drive',
    city: 'Beaumont',
    state: 'TX',
    zipCode: 90114,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '2311 West Way',
    city: 'Fresno',
    state: 'CA',
    zipCode: 87913,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '028 Memorial Park',
    city: 'Dallas',
    state: 'TX',
    zipCode: 21740,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '08438 Haas Park',
    city: 'Manchester',
    state: 'NH',
    zipCode: 89153,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '00016 Hoffman Park',
    city: 'Dallas',
    state: 'TX',
    zipCode: 12648,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '4305 Aberg Avenue',
    city: 'Longview',
    state: 'TX',
    zipCode: 41533,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '68 Forest Run Way',
    city: 'San Antonio',
    state: 'TX',
    zipCode: 13237,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '7615 Carberry Road',
    city: 'Tacoma',
    state: 'WA',
    zipCode: 48470,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '16499 Welch Hill',
    city: 'Lubbock',
    state: 'TX',
    zipCode: 17191,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '4 Prairieview Way',
    city: 'Dayton',
    state: 'OH',
    zipCode: 15615,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '8304 2nd Plaza',
    city: 'Akron',
    state: 'OH',
    zipCode: 79023,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '5712 Superior Parkway',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: 65628,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '57909 Rigney Hill',
    city: 'White Plains',
    state: 'NY',
    zipCode: 30710,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '973 Karstens Avenue',
    city: 'Waterloo',
    state: 'IA',
    zipCode: 14109,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '7 Briar Crest Trail',
    city: 'Durham',
    state: 'NC',
    zipCode: 17944,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '7 Algoma Court',
    city: 'Tyler',
    state: 'TX',
    zipCode: 13064,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '41 Golf View Road',
    city: 'Silver Spring',
    state: 'MD',
    zipCode: 74065,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '578 Ronald Regan Way',
    city: 'Jefferson City',
    state: 'MO',
    zipCode: 91257,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '6 Alpine Alley',
    city: 'Albuquerque',
    state: 'NM',
    zipCode: 61163,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '60 Gina Drive',
    city: 'New Bedford',
    state: 'MA',
    zipCode: 35727,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '1 Chive Terrace',
    city: 'Fresno',
    state: 'CA',
    zipCode: 92411,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '371 Basil Plaza',
    city: 'Fargo',
    state: 'ND',
    zipCode: 51497,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '5 Troy Plaza',
    city: 'Olympia',
    state: 'WA',
    zipCode: 15538,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '47 Johnson Street',
    city: 'Houston',
    state: 'TX',
    zipCode: 24041,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '23 Paget Pass',
    city: 'Raleigh',
    state: 'NC',
    zipCode: 64930,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '9 Bunker Hill Trail',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: 62278,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '8 Monument Road',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: 44352,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '9 Vermont Terrace',
    city: 'Anaheim',
    state: 'CA',
    zipCode: 90409,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '1320 Thackeray Circle',
    city: 'Washington',
    state: 'DC',
    zipCode: 35461,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '94812 Rockefeller Drive',
    city: 'Newark',
    state: 'NJ',
    zipCode: 31019,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '629 Hollow Ridge Center',
    city: 'Miami',
    state: 'FL',
    zipCode: 56876,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '01 Lindbergh Parkway',
    city: 'Fort Worth',
    state: 'TX',
    zipCode: 51162,
    fullfilled: false,
    total: 0,
  },
  {
    streetAddress: '5 Oakridge Hill',
    city: 'New York City',
    state: 'NY',
    zipCode: 83644,
    fullfilled: false,
    total: 0,
  },
];

module.exports = ordersSeed;
