const Order = require('./models/Order');

const ordersSeed = [
  {
    firstName: 'Gail',
    lastName: 'Wreight',
    streetAddress: '65 Spenser Trail',
    state: 'Alabama',
    city: 'Huntsville',
    zipCode: '35805',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Wanda',
    lastName: 'Willoughey',
    streetAddress: '15 Dorton Way',
    state: 'California',
    city: 'Van Nuys',
    zipCode: '91499',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Quintilla',
    lastName: 'Larciere',
    streetAddress: '482 Dawn Junction',
    state: 'Ohio',
    city: 'Columbus',
    zipCode: '43215',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Fidela',
    lastName: 'Quare',
    streetAddress: '489 Paget Lane',
    state: 'California',
    city: 'Sacramento',
    zipCode: '94297',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Deedee',
    lastName: 'Welbrock',
    streetAddress: '210 Upham Circle',
    state: 'Texas',
    city: 'Houston',
    zipCode: '77060',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Aridatha',
    lastName: 'Lorentzen',
    streetAddress: '042 Bartelt Drive',
    state: 'West Virginia',
    city: 'Huntington',
    zipCode: '25705',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Kristan',
    lastName: 'Dawney',
    streetAddress: '24 Northport Terrace',
    state: 'Florida',
    city: 'Panama City',
    zipCode: '32412',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Bess',
    lastName: 'Tezure',
    streetAddress: '2 Rowland Junction',
    state: 'Virginia',
    city: 'Arlington',
    zipCode: '22234',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Sibeal',
    lastName: 'Botwright',
    streetAddress: '553 Anzinger Way',
    state: 'Florida',
    city: 'Daytona Beach',
    zipCode: '32123',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Sidonia',
    lastName: 'Thwaites',
    streetAddress: '2119 Bultman Pass',
    state: 'Illinois',
    city: 'Peoria',
    zipCode: '61629',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Beth',
    lastName: 'Kindleside',
    streetAddress: '3 Rockefeller Center',
    state: 'District of Columbia',
    city: 'Washington',
    zipCode: '20046',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Drugi',
    lastName: 'Ashlee',
    streetAddress: '4 Londonderry Junction',
    state: 'Texas',
    city: 'San Antonio',
    zipCode: '78278',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ollie',
    lastName: 'Tarren',
    streetAddress: '28667 Southridge Pass',
    state: 'Tennessee',
    city: 'Memphis',
    zipCode: '38168',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Kirbee',
    lastName: 'Sobieski',
    streetAddress: '2067 East Plaza',
    state: 'California',
    city: 'San Jose',
    zipCode: '95108',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Glenine',
    lastName: 'Bloggett',
    streetAddress: '16 Bashford Crossing',
    state: 'Pennsylvania',
    city: 'Harrisburg',
    zipCode: '17110',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Fax',
    lastName: 'Trowill',
    streetAddress: '067 Green Alley',
    state: 'Pennsylvania',
    city: 'Pittsburgh',
    zipCode: '15225',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Bernarr',
    lastName: 'Hedley',
    streetAddress: '21307 Calypso Park',
    state: 'Alabama',
    city: 'Birmingham',
    zipCode: '35215',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Bethany',
    lastName: 'Dundredge',
    streetAddress: '524 Buhler Lane',
    state: 'Ohio',
    city: 'Akron',
    zipCode: '44329',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Puff',
    lastName: 'Gresswood',
    streetAddress: '46 2nd Parkway',
    state: 'Ohio',
    city: 'Columbus',
    zipCode: '43226',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Swen',
    lastName: 'Berwick',
    streetAddress: '976 Kedzie Circle',
    state: 'California',
    city: 'Oakland',
    zipCode: '94611',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Kathi',
    lastName: 'Springell',
    streetAddress: '7 Gale Trail',
    state: 'Indiana',
    city: 'Terre Haute',
    zipCode: '47812',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Mikaela',
    lastName: 'Swinburn',
    streetAddress: '4 Rowland Hill',
    state: 'South Carolina',
    city: 'Columbia',
    zipCode: '29215',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ignace',
    lastName: 'Stockford',
    streetAddress: '69 Golf Course Hill',
    state: 'Texas',
    city: 'Dallas',
    zipCode: '75323',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Herta',
    lastName: 'Piborn',
    streetAddress: '1 Mesta Hill',
    state: 'California',
    city: 'Fresno',
    zipCode: '93721',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Karoline',
    lastName: 'De Gregorio',
    streetAddress: '0938 Milwaukee Circle',
    state: 'Missouri',
    city: 'Columbia',
    zipCode: '65218',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Gretchen',
    lastName: 'Peacham',
    streetAddress: '649 Golf Way',
    state: 'South Dakota',
    city: 'Sioux Falls',
    zipCode: '57193',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Rita',
    lastName: 'Pilley',
    streetAddress: '16 Vermont Park',
    state: 'Texas',
    city: 'Lubbock',
    zipCode: '79415',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Terencio',
    lastName: 'Binden',
    streetAddress: '792 Esker Drive',
    state: 'Arizona',
    city: 'Tucson',
    zipCode: '85737',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Peg',
    lastName: 'Hoopper',
    streetAddress: '5 Green Avenue',
    state: 'North Carolina',
    city: 'Winston Salem',
    zipCode: '27116',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Gearalt',
    lastName: 'Cast',
    streetAddress: '15857 Thackeray Street',
    state: 'West Virginia',
    city: 'Huntington',
    zipCode: '25711',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Emlyn',
    lastName: 'Havick',
    streetAddress: '2989 Cody Alley',
    state: 'Texas',
    city: 'Dallas',
    zipCode: '75241',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Whitney',
    lastName: 'Larham',
    streetAddress: '8953 Fulton Crossing',
    state: 'Georgia',
    city: 'Macon',
    zipCode: '31217',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Angelina',
    lastName: 'Manners',
    streetAddress: '62762 Brickson Park Hill',
    state: 'Washington',
    city: 'Spokane',
    zipCode: '99220',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Franz',
    lastName: 'Butson',
    streetAddress: '9391 Shasta Center',
    state: 'Florida',
    city: 'Vero Beach',
    zipCode: '32964',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Claresta',
    lastName: 'Eisold',
    streetAddress: '40 Hudson Way',
    state: 'Texas',
    city: 'Dallas',
    zipCode: '75387',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Eddie',
    lastName: 'Vanichev',
    streetAddress: '2352 Raven Street',
    state: 'Arizona',
    city: 'Gilbert',
    zipCode: '85297',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Latrina',
    lastName: 'Fargher',
    streetAddress: '3 Oak Valley Way',
    state: 'New Jersey',
    city: 'Newark',
    zipCode: '07195',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Sascha',
    lastName: 'Spreag',
    streetAddress: '87330 Hollow Ridge Pass',
    state: 'New York',
    city: 'Jamaica',
    zipCode: '11447',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Randy',
    lastName: 'Silby',
    streetAddress: '8 Claremont Lane',
    state: 'Texas',
    city: 'El Paso',
    zipCode: '88525',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Emory',
    lastName: 'Neno',
    streetAddress: '9322 Dovetail Junction',
    state: 'Louisiana',
    city: 'New Orleans',
    zipCode: '70129',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Cecelia',
    lastName: 'Simm',
    streetAddress: '39089 Green Ridge Trail',
    state: 'North Dakota',
    city: 'Fargo',
    zipCode: '58106',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Putnem',
    lastName: 'Hallard',
    streetAddress: '5 Raven Place',
    state: 'North Carolina',
    city: 'Winston Salem',
    zipCode: '27110',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Licha',
    lastName: 'Gresly',
    streetAddress: '18992 Mayfield Park',
    state: 'District of Columbia',
    city: 'Washington',
    zipCode: '20036',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ranique',
    lastName: 'Bourges',
    streetAddress: '79 Leroy Lane',
    state: 'California',
    city: 'Sacramento',
    zipCode: '94297',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Haslett',
    lastName: 'Oldall',
    streetAddress: '313 Melvin Center',
    state: 'Illinois',
    city: 'Chicago',
    zipCode: '60609',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Crichton',
    lastName: 'Hagwood',
    streetAddress: '7 Red Cloud Parkway',
    state: 'Virginia',
    city: 'Fairfax',
    zipCode: '22036',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Lucho',
    lastName: 'Denington',
    streetAddress: '374 Northwestern Road',
    state: 'Ohio',
    city: 'Cincinnati',
    zipCode: '45228',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Frazer',
    lastName: 'Sapauton',
    streetAddress: '70092 Dexter Street',
    state: 'North Carolina',
    city: 'Charlotte',
    zipCode: '28205',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Arly',
    lastName: 'Cragell',
    streetAddress: '98 Nancy Alley',
    state: 'Texas',
    city: 'Austin',
    zipCode: '78737',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Piotr',
    lastName: 'Cousin',
    streetAddress: '02 Oneill Junction',
    state: 'Illinois',
    city: 'Chicago',
    zipCode: '60669',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Hans',
    lastName: 'Bosch',
    streetAddress: '25491 Drewry Place',
    state: 'New York',
    city: 'Buffalo',
    zipCode: '14269',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Adrea',
    lastName: 'Seago',
    streetAddress: '5241 Atwood Junction',
    state: 'Minnesota',
    city: 'Saint Paul',
    zipCode: '55127',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Lizzy',
    lastName: 'Suttaby',
    streetAddress: '3 Forest Street',
    state: 'Georgia',
    city: 'Macon',
    zipCode: '31210',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Cecile',
    lastName: 'Challace',
    streetAddress: '749 Sloan Avenue',
    state: 'District of Columbia',
    city: 'Washington',
    zipCode: '20380',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Boniface',
    lastName: 'Leidl',
    streetAddress: '9 Roxbury Alley',
    state: 'Florida',
    city: 'Miami',
    zipCode: '33283',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ase',
    lastName: 'Charlon',
    streetAddress: '124 Sherman Plaza',
    state: 'Florida',
    city: 'Lake Worth',
    zipCode: '33462',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ally',
    lastName: 'Luttger',
    streetAddress: '193 Manitowish Trail',
    state: 'New York',
    city: 'Brooklyn',
    zipCode: '11247',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Fanya',
    lastName: 'Canada',
    streetAddress: '690 Caliangt Way',
    state: 'Illinois',
    city: 'Champaign',
    zipCode: '61825',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Devonna',
    lastName: 'Antoniottii',
    streetAddress: '9 Dayton Parkway',
    state: 'Virginia',
    city: 'Roanoke',
    zipCode: '24029',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ruthy',
    lastName: 'Wegenen',
    streetAddress: '49305 Mendota Alley',
    state: 'Tennessee',
    city: 'Memphis',
    zipCode: '38104',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ezra',
    lastName: 'Newling',
    streetAddress: '28370 Saint Paul Drive',
    state: 'California',
    city: 'Fresno',
    zipCode: '93750',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Marysa',
    lastName: 'Sleep',
    streetAddress: '58 Main Circle',
    state: 'California',
    city: 'Sacramento',
    zipCode: '94291',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'El',
    lastName: 'Shilvock',
    streetAddress: '23 Vermont Lane',
    state: 'Maryland',
    city: 'Silver Spring',
    zipCode: '20918',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Molly',
    lastName: 'Matieu',
    streetAddress: '3793 Division Place',
    state: 'Wisconsin',
    city: 'Madison',
    zipCode: '53716',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Linell',
    lastName: 'Peachman',
    streetAddress: '559 Kennedy Point',
    state: 'New York',
    city: 'New York City',
    zipCode: '10039',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Brittani',
    lastName: 'Likly',
    streetAddress: '16 Dryden Parkway',
    state: 'Florida',
    city: 'Hialeah',
    zipCode: '33018',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Hope',
    lastName: 'Yelland',
    streetAddress: '21141 Prairie Rose Trail',
    state: 'Minnesota',
    city: 'Minneapolis',
    zipCode: '55407',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Hanna',
    lastName: 'Dooly',
    streetAddress: '04 Fordem Avenue',
    state: 'New Jersey',
    city: 'Trenton',
    zipCode: '08603',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Stevy',
    lastName: 'Rengger',
    streetAddress: '20 Brickson Park Pass',
    state: 'Texas',
    city: 'Odessa',
    zipCode: '79764',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Roldan',
    lastName: 'Ham',
    streetAddress: '5976 High Crossing Point',
    state: 'Indiana',
    city: 'Gary',
    zipCode: '46406',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Alfredo',
    lastName: 'World',
    streetAddress: '9 Kings Drive',
    state: 'Texas',
    city: 'El Paso',
    zipCode: '88546',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Jackie',
    lastName: 'Hare',
    streetAddress: '8 Brown Parkway',
    state: 'California',
    city: 'Santa Cruz',
    zipCode: '95064',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Freedman',
    lastName: 'Hardwick',
    streetAddress: '4 Anzinger Drive',
    state: 'District of Columbia',
    city: 'Washington',
    zipCode: '20010',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Joshia',
    lastName: 'Hayley',
    streetAddress: '20 Badeau Street',
    state: 'Washington',
    city: 'Olympia',
    zipCode: '98506',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Starla',
    lastName: 'Bernt',
    streetAddress: '5626 Chive Court',
    state: 'New York',
    city: 'Brooklyn',
    zipCode: '11205',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Ivett',
    lastName: 'Ellings',
    streetAddress: '87120 Mccormick Circle',
    state: 'New Mexico',
    city: 'Albuquerque',
    zipCode: '87140',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Georgia',
    lastName: 'Mawson',
    streetAddress: '363 Nobel Court',
    state: 'Florida',
    city: 'Miami',
    zipCode: '33134',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Cherin',
    lastName: 'Balding',
    streetAddress: '48114 Cody Drive',
    state: 'California',
    city: 'Los Angeles',
    zipCode: '90094',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Joannes',
    lastName: 'Greatland',
    streetAddress: '36 Reinke Alley',
    state: 'Arizona',
    city: 'Tempe',
    zipCode: '85284',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Charmine',
    lastName: 'Fencott',
    streetAddress: '9875 Coolidge Terrace',
    state: 'Missouri',
    city: 'Saint Louis',
    zipCode: '63126',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Emilie',
    lastName: 'Sleany',
    streetAddress: '50 Duke Trail',
    state: 'Indiana',
    city: 'Fort Wayne',
    zipCode: '46814',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Lynnell',
    lastName: 'Winborn',
    streetAddress: '726 Crescent Oaks Park',
    state: 'West Virginia',
    city: 'Huntington',
    zipCode: '25709',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Granville',
    lastName: 'Evesque',
    streetAddress: '8 Caliangt Parkway',
    state: 'Michigan',
    city: 'Dearborn',
    zipCode: '48126',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Vivien',
    lastName: 'Lochhead',
    streetAddress: '937 Pond Court',
    state: 'California',
    city: 'Escondido',
    zipCode: '92030',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Annaliese',
    lastName: 'Mc Ilwrick',
    streetAddress: '5011 Gulseth Street',
    state: 'California',
    city: 'San Jose',
    zipCode: '95118',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Samson',
    lastName: 'Lund',
    streetAddress: '9467 Thierer Terrace',
    state: 'Virginia',
    city: 'Roanoke',
    zipCode: '24034',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Sonny',
    lastName: 'Tonn',
    streetAddress: '5460 Shoshone Park',
    state: 'Florida',
    city: 'Lakeland',
    zipCode: '33811',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Silvia',
    lastName: 'Mioni',
    streetAddress: '43078 Dahle Plaza',
    state: 'Oklahoma',
    city: 'Tulsa',
    zipCode: '74141',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Damien',
    lastName: 'Battaille',
    streetAddress: '37 Lindbergh Hill',
    state: 'New York',
    city: 'Albany',
    zipCode: '12262',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Heida',
    lastName: 'Bruton',
    streetAddress: '85 Randy Place',
    state: 'Florida',
    city: 'Orlando',
    zipCode: '32835',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Linnea',
    lastName: 'Dionisetti',
    streetAddress: '736 Nelson Point',
    state: 'Indiana',
    city: 'South Bend',
    zipCode: '46620',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Blanch',
    lastName: 'Hulks',
    streetAddress: '252 Northport Pass',
    state: 'California',
    city: 'San Diego',
    zipCode: '92176',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Tabbi',
    lastName: 'Aldwinckle',
    streetAddress: '42 Tennyson Hill',
    state: 'North Carolina',
    city: 'Charlotte',
    zipCode: '28263',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Kathryne',
    lastName: 'Egdal',
    streetAddress: '7802 Ridgeview Avenue',
    state: 'Illinois',
    city: 'Peoria',
    zipCode: '61614',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Murdock',
    lastName: 'Ondrusek',
    streetAddress: '961 Eggendart Court',
    state: 'Missouri',
    city: 'Kansas City',
    zipCode: '64114',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Lela',
    lastName: 'Eirwin',
    streetAddress: '4 Lawn Crossing',
    state: 'New Jersey',
    city: 'Paterson',
    zipCode: '07522',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Cornelia',
    lastName: 'Maffia',
    streetAddress: '7931 Almo Point',
    state: 'New York',
    city: 'Buffalo',
    zipCode: '14233',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Dale',
    lastName: 'Cullingford',
    streetAddress: '59 4th Hill',
    state: 'Delaware',
    city: 'Wilmington',
    zipCode: '19897',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Tish',
    lastName: 'Noni',
    streetAddress: '7466 Westridge Trail',
    state: 'Texas',
    city: 'Amarillo',
    zipCode: '79159',
    fullfilled: 'no',
    total: 0,
  },
  {
    firstName: 'Melessa',
    lastName: 'Warbys',
    streetAddress: '8 Sutteridge Crossing',
    state: 'Nevada',
    city: 'Reno',
    zipCode: '89519',
    fullfilled: 'no',
    total: 0,
  },
];

module.exports = ordersSeed;
