const plantsSeed = [
  {
    name: "Old Man's Whiskers",
    description: 'Praesent blandit. Nam nulla.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 174,
    inventory: 104,
  },
  {
    name: 'Mexican Bedstraw',
    description: 'Nullam varius. Nulla facilisi.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 159,
    inventory: 60,
  },
  {
    name: 'Gyalidea Lichen',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 53,
    inventory: 15,
  },
  {
    name: 'Dot Lichen',
    description: 'Donec dapibus.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 57,
    inventory: 73,
  },
  {
    name: "Krause's Sorrel",
    description: 'Suspendisse potenti.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 157,
    inventory: 75,
  },
  {
    name: 'Orangefruit Horse-gentian',
    description: 'Phasellus in felis.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 62,
    inventory: 143,
  },
  {
    name: "Bourgeau's Nutrush",
    description: 'Duis mattis egestas metus.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 140,
    inventory: 124,
  },
  {
    name: 'Susanville Milkvetch',
    description: 'Cras non velit nec nisi vulputate nonummy.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 106,
    inventory: 54,
  },
  {
    name: 'Seaside Bittercress',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 37,
    inventory: 134,
  },
  {
    name: 'Kidney Lichen',
    description: 'Cras non velit nec nisi vulputate nonummy.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 58,
    inventory: 120,
  },
  {
    name: 'Fescue',
    description: 'Suspendisse potenti.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 187,
    inventory: 80,
  },
  {
    name: 'Scheel Creek Beardtongue',
    description: 'Cras pellentesque volutpat dui.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 195,
    inventory: 61,
  },
  {
    name: 'Roadside Woodrose',
    description: 'In congue.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 43,
    inventory: 62,
  },
  {
    name: 'Sphagnum',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 123,
    inventory: 61,
  },
  {
    name: 'Gulf Searocket',
    description:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 161,
    inventory: 144,
  },
  {
    name: 'Redroot Cryptantha',
    description:
      'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 101,
    inventory: 132,
  },
  {
    name: 'Water Dead And Awake',
    description: 'Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 87,
    inventory: 88,
  },
  {
    name: 'Rough Chervil',
    description: 'Donec vitae nisi.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 71,
    inventory: 103,
  },
  {
    name: 'Alpine Jewelflower',
    description: 'Suspendisse potenti. In eleifend quam a odio.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 193,
    inventory: 150,
  },
  {
    name: "Frankton's Saltbush",
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 78,
    inventory: 86,
  },
  {
    name: 'Lecidea Lichen',
    description: 'Aliquam sit amet diam in magna bibendum imperdiet.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 40,
    inventory: 14,
  },
  {
    name: 'Awnless Leastdaisy',
    description: 'Nunc nisl.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 60,
    inventory: 41,
  },
  {
    name: 'Large Whorled Pogonia',
    description: 'Morbi ut odio.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 112,
    inventory: 115,
  },
  {
    name: 'Lily',
    description: 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 186,
    inventory: 76,
  },
  {
    name: 'Kohala Summit Melicope',
    description:
      'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 98,
    inventory: 81,
  },
  {
    name: 'Southern Flatsedge',
    description: 'Nunc purus. Phasellus in felis.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 65,
    inventory: 30,
  },
  {
    name: 'Hairy-lemma Barley',
    description: 'Maecenas ut massa quis augue luctus tincidunt.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 151,
    inventory: 21,
  },
  {
    name: 'Ajowan Caraway',
    description:
      'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 107,
    inventory: 46,
  },
  {
    name: 'Bluntpod Bundleflower',
    description:
      'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 179,
    inventory: 101,
  },
  {
    name: 'Fourspike Heliotrope',
    description: 'Donec semper sapien a libero. Nam dui.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 76,
    inventory: 42,
  },
  {
    name: "'aiakanene",
    description: 'Suspendisse potenti. Nullam porttitor lacus at turpis.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 104,
    inventory: 68,
  },
  {
    name: 'Crabseye Lichen',
    description: 'Vivamus tortor.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 35,
    inventory: 61,
  },
  {
    name: "Drew's Silky Lupine",
    description: 'Proin eu mi. Nulla ac enim.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 152,
    inventory: 81,
  },
  {
    name: 'Fingergrass',
    description: 'Nam dui.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 127,
    inventory: 148,
  },
  {
    name: 'Mt. Lassen Fleabane',
    description:
      'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 180,
    inventory: 106,
  },
  {
    name: 'Anthracothecium Lichen',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 184,
    inventory: 89,
  },
  {
    name: 'Forest Spleenwort',
    description: 'Phasellus in felis.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 179,
    inventory: 104,
  },
  {
    name: 'Tropidia',
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 189,
    inventory: 27,
  },
  {
    name: 'Hill Buckwheat',
    description:
      'Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 72,
    inventory: 106,
  },
  {
    name: 'Selenia',
    description: 'Integer ac leo. Pellentesque ultrices mattis odio.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 144,
    inventory: 40,
  },
  {
    name: 'Greenland Pondweed',
    description: 'Phasellus in felis. Donec semper sapien a libero.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 122,
    inventory: 93,
  },
  {
    name: 'Little Lemonhead',
    description: 'In hac habitasse platea dictumst.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 159,
    inventory: 143,
  },
  {
    name: 'Ammi',
    description: 'Proin eu mi. Nulla ac enim.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 146,
    inventory: 116,
  },
  {
    name: 'Big-mouth Star Orchid',
    description: 'Morbi a ipsum.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 59,
    inventory: 67,
  },
  {
    name: 'Redding Buckwheat',
    description: 'Etiam vel augue.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 161,
    inventory: 65,
  },
  {
    name: 'San Gabriel Bluecup',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 158,
    inventory: 69,
  },
  {
    name: 'Skin Lichen',
    description:
      'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    sizeFilter: 3,
    size: 'extra large',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 1,
    difficulty: 'No-fuss — Carefree',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 138,
    inventory: 95,
  },
  {
    name: 'Brothera Moss',
    description:
      'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
    sizeFilter: 4,
    size: 'extra large',
    lightFilter: 3,
    light: 'Partial to Bright — Bright indirect to full sun',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 49,
    inventory: 114,
  },
  {
    name: 'Mountain-avens',
    description: 'Integer a nibh.',
    sizeFilter: 1,
    size: 'small',
    lightFilter: 1,
    light: 'Low to Partial — Low to bright indirect light',
    difficultyFilter: 2,
    difficulty: 'Easy — Relatively low maintenance',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 101,
    inventory: 48,
  },
  {
    name: 'Cucubano',
    description: 'Phasellus in felis.',
    sizeFilter: 2,
    size: 'medium',
    lightFilter: 2,
    light: 'Medium — Bright indirect light',
    difficultyFilter: 3,
    difficulty: 'Moderate — Needs a bit of extra care',
    petFriendly: 'no',
    petFilter: false,
    airCleaner: 'no',
    img: '/images/yellowcan.jpeg',
    price: 173,
    inventory: 90,
  },
];

module.exports = plantsSeed;
