const plantsSeed = [
  {
    name: 'Golden Hedgehyssop',
    description: 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    size: 1,
    light: 1,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 88,
    inventory: 187,
  },
  {
    name: 'Stemless Dwarf-cudweed',
    description:
      'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',
    size: 1,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 116,
    inventory: 19,
  },
  {
    name: 'Trailing Krameria',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
    size: 3,
    light: 2,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 106,
    inventory: 36,
  },
  {
    name: 'Hypotrachyna Lichen',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
    size: 3,
    light: 1,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 83,
    inventory: 133,
  },
  {
    name: 'Yellow Sedge',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
    size: 3,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 44,
    inventory: 9,
  },
  {
    name: 'Tansy Pepperweed',
    description:
      'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
    size: 2,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 158,
    inventory: 13,
  },
  {
    name: "Geyer's Oniongrass",
    description:
      'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
    size: 4,
    light: 3,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 56,
    inventory: 175,
  },
  {
    name: 'Northern Twayblade',
    description: 'Duis mattis egestas metus. Aenean fermentum.',
    size: 2,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 155,
    inventory: 132,
  },
  {
    name: 'Slash Pine',
    description:
      'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
    size: 2,
    light: 3,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 43,
    inventory: 71,
  },
  {
    name: 'Goetzea',
    description:
      'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    size: 3,
    light: 1,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 39,
    inventory: 164,
  },
  {
    name: 'Black-box',
    description: 'In congue. Etiam justo.',
    size: 4,
    light: 3,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 139,
    inventory: 169,
  },
  {
    name: 'Cigar Flower',
    description:
      'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    size: 2,
    light: 2,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 149,
    inventory: 44,
  },
  {
    name: 'Latin American Orchid',
    description:
      'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.',
    size: 4,
    light: 3,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 79,
    inventory: 87,
  },
  {
    name: 'Clustered Broomrape',
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
    size: 3,
    light: 2,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 147,
    inventory: 91,
  },
  {
    name: 'Rinodina Lichen',
    description: 'Pellentesque at nulla. Suspendisse potenti.',
    size: 3,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 81,
    inventory: 12,
  },
  {
    name: 'Spotflower',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.',
    size: 1,
    light: 3,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 131,
    inventory: 147,
  },
  {
    name: 'Yellow Gilia',
    description:
      'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',
    size: 3,
    light: 1,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 155,
    inventory: 76,
  },

  {
    name: 'Crowberry',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    size: 1,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 152,
    inventory: 49,
  },
  {
    name: 'Bearded Jewelflower',
    description: 'Aliquam erat volutpat. In congue.',
    size: 3,
    light: 3,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 57,
    inventory: 139,
  },
  {
    name: 'American Dwarf Mistletoe',
    description: 'Pellentesque ultrices mattis odio. Donec vitae nisi.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 71,
    inventory: 102,
  },
  {
    name: 'Bitterbrush',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    size: 1,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 101,
    inventory: 17,
  },
  {
    name: 'Texas Madrone',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    size: 3,
    light: 3,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 58,
    inventory: 163,
  },
  {
    name: 'California Ash',
    description: 'Integer a nibh. In quis justo.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 119,
    inventory: 175,
  },
  {
    name: 'Asiatic Mangrove',
    description:
      'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    size: 2,
    light: 1,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 65,
    inventory: 12,
  },
  {
    name: 'Cowhorn Orchid',
    description:
      'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    size: 1,
    light: 1,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 104,
    inventory: 136,
  },
  {
    name: 'Trinity Buckwheat',
    description:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
    size: 1,
    light: 2,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 140,
    inventory: 65,
  },
  {
    name: 'Pomegranate',
    description: 'Morbi a ipsum. Integer a nibh.',
    size: 2,
    light: 1,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 36,
    inventory: 58,
  },
  {
    name: 'Japanese Spindletree',
    description:
      'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
    size: 1,
    light: 3,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 39,
    inventory: 188,
  },
  {
    name: 'Central Idaho Penstemon',
    description:
      'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    size: 4,
    light: 2,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 154,
    inventory: 99,
  },
  {
    name: 'Cutleaf Gumweed',
    description: 'Integer a nibh. In quis justo.',
    size: 3,
    light: 2,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 60,
    inventory: 156,
  },
  {
    name: 'Eyebright',
    description: 'Proin risus. Praesent lectus.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 123,
    inventory: 99,
  },
  {
    name: 'Carolina Wild Petunia',
    description:
      'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
    size: 2,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 38,
    inventory: 149,
  },
  {
    name: 'Spreading Windmill Grass',
    description: 'In sagittis dui vel nisl. Duis ac nibh.',
    size: 2,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 37,
    inventory: 6,
  },
  {
    name: 'Lentil Vetch',
    description:
      'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
    size: 2,
    light: 2,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 108,
    inventory: 41,
  },
  {
    name: 'Dicranum Moss',
    description: 'Nulla nisl. Nunc nisl.',
    size: 2,
    light: 1,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 101,
    inventory: 145,
  },
  {
    name: "Phillips' Cliff Fern",
    description: 'In quis justo. Maecenas rhoncus aliquam lacus.',
    size: 3,
    light: 1,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 161,
    inventory: 89,
  },
  {
    name: "Gooding's Gooseberry",
    description: 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',
    size: 2,
    light: 3,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 72,
    inventory: 65,
  },
  {
    name: 'Slimspike Threeawn',
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
    size: 1,
    light: 3,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 95,
    inventory: 150,
  },
  {
    name: 'St. Thomas Lidpod',
    description:
      'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.',
    size: 4,
    light: 3,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 152,
    inventory: 9,
  },
  {
    name: 'Open Clover',
    description:
      'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    size: 1,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 107,
    inventory: 114,
  },
  {
    name: 'Breakbill',
    description:
      'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',
    size: 1,
    light: 3,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 89,
    inventory: 147,
  },
  {
    name: 'Yerba',
    description: 'Quisque ut erat. Curabitur gravida nisi at nibh.',
    size: 1,
    light: 2,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 140,
    inventory: 12,
  },
  {
    name: 'European Chestnut',
    description: 'Vivamus tortor. Duis mattis egestas metus.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 68,
    inventory: 88,
  },
  {
    name: 'Rough Hawkweed',
    description:
      'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    size: 1,
    light: 2,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 142,
    inventory: 54,
  },
  {
    name: 'Siberian Oatgrass',
    description:
      'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    size: 4,
    light: 2,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 114,
    inventory: 3,
  },
  {
    name: "Clinton's Bulrush",
    description:
      'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    size: 1,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 143,
    inventory: 119,
  },
  {
    name: 'Slender Bulrush',
    description: 'Integer a nibh. In quis justo.',
    size: 2,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 92,
    inventory: 116,
  },
  {
    name: 'Dinosaur Milkvetch',
    description: 'Suspendisse potenti. In eleifend quam a odio.',
    size: 4,
    light: 1,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 111,
    inventory: 143,
  },
  {
    name: 'Balsam Fir',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    size: 1,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 133,
    inventory: 59,
  },
  {
    name: 'Sessileleaf Scurvygrass',
    description: 'Nunc purus. Phasellus in felis.',
    size: 3,
    light: 3,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 135,
    inventory: 187,
  },
  {
    name: 'Meadow Alexanders',
    description: 'Aliquam non mauris. Morbi non lectus.',
    size: 3,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 117,
    inventory: 28,
  },
  {
    name: 'Nevada Pottia Moss',
    description: 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    size: 2,
    light: 2,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 111,
    inventory: 86,
  },
  {
    name: 'Mexican Umbrella Fern',
    description: 'Vivamus tortor. Duis mattis egestas metus.',
    size: 4,
    light: 3,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 124,
    inventory: 58,
  },
  {
    name: 'Alien Rimmed Lichen',
    description:
      'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.',
    size: 1,
    light: 3,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 36,
    inventory: 169,
  },
  {
    name: 'Coscinodon Moss',
    description: 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',
    size: 1,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 108,
    inventory: 136,
  },
  {
    name: 'Dixie Whitetop Aster',
    description: 'Pellentesque ultrices mattis odio. Donec vitae nisi.',
    size: 1,
    light: 3,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 62,
    inventory: 199,
  },
  {
    name: 'Navel Cornsalad',
    description:
      'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 42,
    inventory: 65,
  },
  {
    name: 'Orange Lichen',
    description: 'Duis bibendum. Morbi non quam nec dui luctus rutrum.',
    size: 4,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 67,
    inventory: 133,
  },
  {
    name: 'Kuroiwa Grass',
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.',
    size: 3,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 103,
    inventory: 12,
  },
  {
    name: 'Gentian',
    description: 'Integer a nibh. In quis justo.',
    size: 1,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 144,
    inventory: 19,
  },
  {
    name: 'Corky Spindletree',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',
    size: 2,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 161,
    inventory: 15,
  },
  {
    name: 'Flowering Plum',
    description: 'Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    size: 1,
    light: 2,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 43,
    inventory: 68,
  },
  {
    name: 'Black Sweetwood',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.',
    size: 1,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 74,
    inventory: 154,
  },
  {
    name: 'Slender Cottongrass',
    description: 'Fusce consequat. Nulla nisl.',
    size: 4,
    light: 1,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 111,
    inventory: 99,
  },
  {
    name: 'Umtanum Desertparsley',
    description: 'Donec semper sapien a libero. Nam dui.',
    size: 2,
    light: 1,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 82,
    inventory: 186,
  },
  {
    name: 'Hairy White Oldfield Aster',
    description:
      'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
    size: 4,
    light: 1,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 40,
    inventory: 92,
  },
  {
    name: 'Bonneville Shootingstar',
    description:
      'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.',
    size: 2,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 93,
    inventory: 14,
  },
  {
    name: 'Dot Lichen',
    description: 'Donec semper sapien a libero. Nam dui.',
    size: 4,
    light: 2,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 90,
    inventory: 178,
  },
  {
    name: 'Smallleaf Shield Lichen',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
    size: 1,
    light: 1,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 39,
    inventory: 85,
  },
  {
    name: 'Cotta Grass',
    description: 'In sagittis dui vel nisl. Duis ac nibh.',
    size: 1,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 119,
    inventory: 64,
  },
  {
    name: 'Angled Mistletoe',
    description: 'Integer a nibh. In quis justo.',
    size: 1,
    light: 1,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 149,
    inventory: 78,
  },
  {
    name: 'Giant Dropseed',
    description: 'Aenean sit amet justo. Morbi ut odio.',
    size: 2,
    light: 2,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 84,
    inventory: 125,
  },
  {
    name: 'Prescott Orchid',
    description: 'Praesent blandit. Nam nulla.',
    size: 3,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 75,
    inventory: 97,
  },
  {
    name: 'Speckled Spur Flower',
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',
    size: 4,
    light: 2,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 159,
    inventory: 89,
  },
  {
    name: 'Swamp Tickseed',
    description:
      'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
    size: 1,
    light: 3,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 60,
    inventory: 56,
  },
  {
    name: 'Arctic Bentgrass',
    description:
      'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.',
    size: 2,
    light: 1,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 139,
    inventory: 35,
  },
  {
    name: 'Wimmera Ryegrass',
    description: 'Pellentesque at nulla. Suspendisse potenti.',
    size: 1,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 116,
    inventory: 41,
  },
  {
    name: "Rapp's Shell Lichen",
    description: 'Aenean lectus. Pellentesque eget nunc.',
    size: 1,
    light: 3,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 91,
    inventory: 160,
  },
  {
    name: 'Treedaisy',
    description:
      'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
    size: 4,
    light: 2,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 129,
    inventory: 80,
  },
  {
    name: 'Mottled Tuberose',
    description:
      'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    size: 4,
    light: 1,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 128,
    inventory: 149,
  },
  {
    name: 'Chickweed Oxytheca',
    description:
      'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.',
    size: 3,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 153,
    inventory: 126,
  },
  {
    name: 'Dwarf Alpine Hawksbeard',
    description: 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.',
    size: 1,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 94,
    inventory: 49,
  },
  {
    name: 'Merced Clarkia',
    description: 'Praesent blandit. Nam nulla.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 42,
    inventory: 19,
  },
  {
    name: "Polunin's Rim Lichen",
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
    size: 4,
    light: 1,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 56,
    inventory: 24,
  },
  {
    name: 'Flax',
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',
    size: 4,
    light: 3,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 36,
    inventory: 68,
  },
  {
    name: "Lemmon's Alkaligrass",
    description:
      'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',
    size: 1,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 152,
    inventory: 199,
  },
  {
    name: 'Matted Paspalum',
    description:
      'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',
    size: 4,
    light: 3,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 54,
    inventory: 155,
  },
  {
    name: "Muhlenberg's Sedge",
    description:
      'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
    size: 4,
    light: 3,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 163,
    inventory: 19,
  },
  {
    name: 'Boston Ivy',
    description:
      'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',
    size: 1,
    light: 1,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 102,
    inventory: 158,
  },
  {
    name: 'Cordyline',
    description:
      'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
    size: 4,
    light: 3,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 61,
    inventory: 120,
  },
  {
    name: "Tweedy's Plantain",
    description: 'Nulla nisl. Nunc nisl.',
    size: 1,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 132,
    inventory: 8,
  },
  {
    name: 'Point Reyes Bentgrass',
    description: 'Morbi non quam nec dui luctus rutrum. Nulla tellus.',
    size: 4,
    light: 1,
    difficulty: 1,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 100,
    inventory: 179,
  },
  {
    name: 'Alexandrian Senna',
    description:
      'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',
    size: 2,
    light: 1,
    difficulty: 2,
    petFriendly: 'yes',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 137,
    inventory: 167,
  },
  {
    name: 'African Basil',
    description: 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.',
    size: 2,
    light: 1,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 35,
    inventory: 151,
  },
  {
    name: 'Hymenostylium Moss',
    description: 'In quis justo. Maecenas rhoncus aliquam lacus.',
    size: 2,
    light: 2,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 83,
    inventory: 169,
  },
  {
    name: 'Stinking Camphorweed',
    description:
      'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    size: 4,
    light: 3,
    difficulty: 3,
    petFriendly: 'yes',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 102,
    inventory: 22,
  },
  {
    name: "Constance's Phacelia",
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',
    size: 1,
    light: 3,
    difficulty: 1,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 75,
    inventory: 192,
  },
  {
    name: 'Dupoa',
    description:
      'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
    size: 4,
    light: 1,
    difficulty: 2,
    petFriendly: 'no',
    airCleaner: true,
    img: '/images/yellowcan.jpeg',
    price: 59,
    inventory: 91,
  },
  {
    name: 'Purplestem Angelica',
    description:
      'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
    size: 3,
    light: 3,
    difficulty: 3,
    petFriendly: 'no',
    airCleaner: false,
    img: '/images/yellowcan.jpeg',
    price: 99,
    inventory: 3,
  },
];

module.exports = plantsSeed;
