const usersSeed = [
  {
    firstName: 'Admin',
    lastName: 'Istrator',
    phoneNumber: '452-117-1110',
    birthdate: '06/04/1988',
    email: 'admin@gmail.com',
    password: 'admin',
    isAdmin: true,
  },
  {
    firstName: 'Michelle',
    lastName: 'Lauxmann',
    phoneNumber: '564-819-3237',
    birthdate: '04/02/1985',
    email: 'mlauxmann1@time.com',
    password: '6Pb0XRT',
    isAdmin: false,
  },
  {
    firstName: 'Pam',
    lastName: 'Toderini',
    phoneNumber: '369-302-8451',
    birthdate: '07/04/1942',
    email: 'ptoderini2@bbc.co.uk',
    password: 'NEGwHlKB',
    isAdmin: false,
  },
  {
    firstName: 'Aland',
    lastName: 'Itter',
    phoneNumber: '680-518-5526',
    birthdate: '06/17/1914',
    email: 'aitter3@yahoo.co.jp',
    password: 'mw1lFuf9',
    isAdmin: false,
  },
  {
    firstName: 'Faith',
    lastName: 'Cashman',
    phoneNumber: '235-742-1517',
    birthdate: '02/16/1950',
    email: 'fcashman4@godaddy.com',
    password: '1XewLbTVqt',
    isAdmin: false,
  },
  {
    firstName: 'Gerhardt',
    lastName: 'Brinkman',
    phoneNumber: '587-701-8744',
    birthdate: '06/24/1946',
    email: 'gbrinkman5@amazon.co.jp',
    password: 'DZoepSPd',
    isAdmin: false,
  },
  {
    firstName: 'Tiphani',
    lastName: 'Kimbley',
    phoneNumber: '880-812-1199',
    birthdate: '10/05/1924',
    email: 'tkimbley6@uol.com.br',
    password: 'AMN8FhRgKp',
    isAdmin: false,
  },
  {
    firstName: 'Jaymie',
    lastName: 'Ismead',
    phoneNumber: '544-662-6060',
    birthdate: '04/22/1909',
    email: 'jismead7@github.io',
    password: 'W8PWydlIcbw',
    isAdmin: false,
  },
  {
    firstName: 'Brinna',
    lastName: 'Breede',
    phoneNumber: '845-531-1260',
    birthdate: '10/06/1902',
    email: 'bbreede8@mac.com',
    password: 'Se3SVDYAc9',
    isAdmin: false,
  },
  {
    firstName: 'Angel',
    lastName: 'Looby',
    phoneNumber: '131-873-5929',
    birthdate: '11/21/1976',
    email: 'alooby9@posterous.com',
    password: '3Ppqrm',
    isAdmin: false,
  },
  {
    firstName: 'Fulvia',
    lastName: 'Langmead',
    phoneNumber: '419-124-2505',
    birthdate: '05/05/1930',
    email: 'flangmeada@pbs.org',
    password: '6LVjtjj',
    isAdmin: false,
  },
  {
    firstName: 'Kermie',
    lastName: 'Argrave',
    phoneNumber: '888-859-6314',
    birthdate: '10/30/1937',
    email: 'kargraveb@blog.com',
    password: 'jRVQ1YC491',
    isAdmin: false,
  },
  {
    firstName: 'Ramonda',
    lastName: 'Blyth',
    phoneNumber: '192-658-1496',
    birthdate: '06/25/1999',
    email: 'rblythc@intel.com',
    password: 'CUY5BZr35',
    isAdmin: false,
  },
  {
    firstName: 'Nixie',
    lastName: 'Dradey',
    phoneNumber: '331-223-1236',
    birthdate: '05/17/1929',
    email: 'ndradeyd@people.com.cn',
    password: 'kJgdmv',
    isAdmin: false,
  },
  {
    firstName: 'Morey',
    lastName: 'Newiss',
    phoneNumber: '704-495-8020',
    birthdate: '01/04/1934',
    email: 'mnewisse@free.fr',
    password: 'zRPV82NuY',
    isAdmin: false,
  },
  {
    firstName: 'Timothea',
    lastName: 'Loud',
    phoneNumber: '569-778-5872',
    birthdate: '05/21/1992',
    email: 'tloudf@ed.gov',
    password: '88AH661c6m',
    isAdmin: false,
  },
  {
    firstName: 'Shane',
    lastName: 'Ide',
    phoneNumber: '519-671-8662',
    birthdate: '04/21/1904',
    email: 'sideg@shop-pro.jp',
    password: 'h0SBL6M',
    isAdmin: false,
  },
  {
    firstName: 'Madalena',
    lastName: 'Stredder',
    phoneNumber: '693-739-1273',
    birthdate: '08/24/1991',
    email: 'mstredderh@1688.com',
    password: 'SThwm5Ebp',
    isAdmin: false,
  },
  {
    firstName: 'Meryl',
    lastName: 'Gersam',
    phoneNumber: '286-337-6784',
    birthdate: '09/09/1966',
    email: 'mgersami@privacy.gov.au',
    password: 'JXOcEBVBGpS',
    isAdmin: false,
  },
  {
    firstName: 'Wilbert',
    lastName: 'Romayne',
    phoneNumber: '243-949-5942',
    birthdate: '08/31/1938',
    email: 'wromaynej@buzzfeed.com',
    password: 'PLOKUNo',
    isAdmin: false,
  },
  {
    firstName: 'Vladimir',
    lastName: 'Jeppe',
    phoneNumber: '380-899-1601',
    birthdate: '07/21/2004',
    email: 'vjeppek@t.co',
    password: 'DA2aRDm',
    isAdmin: false,
  },
  {
    firstName: 'Appolonia',
    lastName: 'Sjollema',
    phoneNumber: '934-663-5409',
    birthdate: '03/23/1998',
    email: 'asjollemal@umich.edu',
    password: 'LiHe88',
    isAdmin: false,
  },
  {
    firstName: 'Bronnie',
    lastName: 'McRorie',
    phoneNumber: '882-335-1793',
    birthdate: '03/01/1924',
    email: 'bmcroriem@youku.com',
    password: 'pcKSTWfOQ',
    isAdmin: false,
  },
  {
    firstName: 'Debora',
    lastName: 'Goodding',
    phoneNumber: '701-483-7600',
    birthdate: '05/01/1920',
    email: 'dgooddingn@hubpages.com',
    password: 'tbjANEP9PF',
    isAdmin: false,
  },
  {
    firstName: 'Vanessa',
    lastName: 'Eskriett',
    phoneNumber: '585-953-1349',
    birthdate: '08/30/1970',
    email: 'veskrietto@lycos.com',
    password: '1xH6vrAvuq',
    isAdmin: false,
  },
  {
    firstName: 'Kearney',
    lastName: 'Juett',
    phoneNumber: '109-952-3506',
    birthdate: '02/27/1969',
    email: 'kjuettp@nationalgeographic.com',
    password: 'mai548X',
    isAdmin: false,
  },
  {
    firstName: 'Flemming',
    lastName: 'Owens',
    phoneNumber: '440-872-6428',
    birthdate: '12/28/1958',
    email: 'fowensq@wiley.com',
    password: 'cu1b7C3q',
    isAdmin: false,
  },
  {
    firstName: 'Esteban',
    lastName: 'Gai',
    phoneNumber: '170-976-2843',
    birthdate: '07/22/1997',
    email: 'egair@gmpg.org',
    password: 'jyfye6X',
    isAdmin: false,
  },
  {
    firstName: 'Joyous',
    lastName: 'Way',
    phoneNumber: '235-373-8768',
    birthdate: '12/11/1980',
    email: 'jways@alibaba.com',
    password: '9DRPiqwizXCk',
    isAdmin: false,
  },
  {
    firstName: 'Flo',
    lastName: 'Shier',
    phoneNumber: '325-726-3908',
    birthdate: '04/16/1906',
    email: 'fshiert@w3.org',
    password: 'St8aI67h0',
    isAdmin: false,
  },
  {
    firstName: 'Tasha',
    lastName: 'Ivantsov',
    phoneNumber: '807-223-9787',
    birthdate: '03/06/1962',
    email: 'tivantsovu@washington.edu',
    password: '07zdSZgV',
    isAdmin: false,
  },
  {
    firstName: 'Karena',
    lastName: 'Engledow',
    phoneNumber: '318-161-7531',
    birthdate: '07/29/1988',
    email: 'kengledowv@harvard.edu',
    password: '8A9W0NZAnp1F',
    isAdmin: false,
  },
  {
    firstName: 'Gavin',
    lastName: 'Umbert',
    phoneNumber: '248-764-5247',
    birthdate: '10/19/1978',
    email: 'gumbertw@netlog.com',
    password: 'VkyPp1',
    isAdmin: false,
  },
  {
    firstName: 'Michal',
    lastName: 'Penkethman',
    phoneNumber: '914-812-5974',
    birthdate: '11/29/2004',
    email: 'mpenkethman2f@unesco.org',
    password: 'Z5szee',
    isAdmin: false,
  },
];
module.exports = usersSeed;
